server:
  port: 8080

spring:
  data:
    maria:
      jdbc-url: jdbc:mariadb://rds-mariadb.cnnvh499ujuu.us-west-1.rds.amazonaws.com:3306/wickies?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: wickies
      password: 12345678
  jpa:
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true